public class EmailMessageConstants {
 
    public static final string StatusReopen = 'Re-Opened';
    public static final string StatusReceived = 'Customer Response Received';
    public static final string StatusAwaiting ='Waiting for Customer Reply';
    public static final string StatusNew ='New';
    public static final List<String> ThankYouMsg = new List<String> {'Thanks','Thank You','Tks'};
    public static final List<String> QuestMesg = new List<String> {'Question','?'};
}